### ISSUE TITLE
Breakage: app crash - 2021-01-19

### ISSUE THREAD

**Issue by xinbenlv** [google/wikiloop-doublecheck#387]
All prod, canary and WMF instance down. Suspecting MongoDB having issue.

```
2021-01-19T16:11:20.470784+00:00 app[web.1]: /app/node_modules/mongodb-core/lib/sessions.js:134
2021-01-19T16:11:20.470784+00:00 app[web.1]: if (typeof callback === 'function') callback(null, null);
2021-01-19T16:11:20.470785+00:00 app[web.1]: ^
2021-01-19T16:11:20.470869+00:00 app[web.1]: Error: Error creating index: user is not allowed to do action [createIndex] on [heroku_00w6ld63.system.indexes]
2021-01-19T16:11:20.470870+00:00 app[web.1]: at /app/node_modules/connect-mongodb-session/index.js:89:23
2021-01-19T16:11:20.470871+00:00 app[web.1]: at /app/node_modules/connect-mongodb-session/node_modules/mongodb/lib/utils.js:411:14
2021-01-19T16:11:20.470871+00:00 app[web.1]: at /app/node_modules/connect-mongodb-session/node_modules/mongodb/lib/utils.js:397:27
2021-01-19T16:11:20.470872+00:00 app[web.1]: at ClientSession.endSession (/app/node_modules/mongodb-core/lib/sessions.js:134:41)
2021-01-19T16:11:20.470872+00:00 app[web.1]: at executeCallback (/app/node_modules/connect-mongodb-session/node_modules/mongodb/lib/utils.js:395:17)
2021-01-19T16:11:20.470872+00:00 app[web.1]: at handleCallback (/app/node_modules/connect-mongodb-session/node_modules/mongodb/lib/utils.js:128:55)
2021-01-19T16:11:20.470873+00:00 app[web.1]: at /app/node_modules/connect-mongodb-session/node_modules/mongodb/lib/operations/db_ops.js:326:25
2021-01-19T16:11:20.470873+00:00 app[web.1]: at handler (/app/node_modules/mongodb-core/lib/topologies/replset.js:1157:14)
2021-01-19T16:11:20.470874+00:00 app[web.1]: at /app/node_modules/mongodb-core/lib/connection/pool.js:397:18
2021-01-19T16:11:20.470874+00:00 app[web.1]: at processTicksAndRejections (internal/process/task_queues.js:79:11)
2021-01-19T16:11:20.539050+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2021-01-19T16:11:20.539482+00:00 app[web.1]: npm ERR! errno 1
2021-01-19T16:11:20.541242+00:00 app[web.1]: npm ERR! wikiloop-doublecheck@4.1.0 start: `cross-env NODE_ENV=production npx ts-node -r tsconfig-paths/register --project tsconfig.json server/index.ts`
2021-01-19T16:11:20.541472+00:00 app[web.1]: npm ERR! Exit status 1
2021-01-19T16:11:20.541909+00:00 app[web.1]: npm ERR!
2021-01-19T16:11:20.542082+00:00 app[web.1]: npm ERR! Failed at the wikiloop-doublecheck@4.1.0 start script.
2021-01-19T16:11:20.542152+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-01-19T16:11:20.965137+00:00 app[web.1]:
2021-01-19T16:11:20.965340+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2021-01-19T16:11:20.965439+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2021-01-19T16_11_20_542Z-debug.log
2021-01-19T16:11:21.027148+00:00 heroku[web.1]: Process exited with status 1
2021-01-19T16:11:21.070421+00:00 heroku[web.1]: State changed from starting to crashed
```

**Comment by xinbenlv** [comment]
After debugging, it was due to 

```
Jan 18 18:00:03 wikiloop-doublecheck-prod app[web] info MongoError: you are over your space quota, using 2053 MB of 2048 MB
Jan 18 18:00:03 wikiloop-doublecheck-prod app[web] info     at Connection.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/core/connection/pool.js:460:61)
Jan 18 18:00:03 wikiloop-doublecheck-prod app[web] info     at Connection.emit (events.js:311:20)
Jan 18 18:00:03 wikiloop-doublecheck-prod app[web] info     at Connection.EventEmitter.emit (domain.js:482:12)
Jan 18 18:00:03 wikiloop-doublecheck-prod app[web] info     at processMessage (/app/node_modules/mongoose/node_modules/mongodb/lib/core/connection/connection.js:368:10)
Jan 18 18:00:03 wikiloop-doublecheck-prod app[web] info     at TLSSocket.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/core/connection/connection.js:537:15)
Jan 18 18:00:03 wikiloop-doublecheck-prod app[web] info     at TLSSocket.emit (events.js:311:20)
Jan 18 18:00:03 wikiloop-doublecheck-prod app[web] info     at TLSSocket.EventEmitter.emit (domain.js:482:12)
Jan 18 18:00:03 wikiloop-doublecheck-prod app[web] info     at addChunk (_stream_readable.js:294:12)
Jan 18 18:00:03 wikiloop-doublecheck-prod app[web] info     at readableAddChunk (_stream_readable.js:275:11)
Jan 18 18:00:03 wikiloop-doublecheck-prod app[web] info     at TLSSocket.Readable.push (_stream_readable.js:209:10)
Jan 18 18:00:03 wikiloop-doublecheck-prod app[web] info     at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23) {
Jan 18 18:00:03 wikiloop-doublecheck-prod app[web] info   ok: 0,
Jan 18 18:00:03 wikiloop-doublecheck-prod app[web] info   errmsg: 'you are over your space quota, using 2053 MB of 2048 MB',
Jan 18 18:00:03 wikiloop-doublecheck-prod app[web] info   code: 8000,
Jan 18 18:00:03 wikiloop-doublecheck-prod app[web] info   codeName: 'AtlasError',
Jan 18 18:00:03 wikiloop-doublecheck-prod app[web] info   name: 'MongoError',
Jan 18 18:00:03 wikiloop-doublecheck-prod app[web] info   [Symbol(mongoErrorContextSymbol)]: {}
Jan 18 18:00:03 wikiloop-doublecheck-prod app[web] info }
Jan 18 18:00:03 wikiloop-doublecheck-prod app[web] info Promise {
Jan 18 18:00:03 wikiloop-doublecheck-prod app[web] info   <rejected> MongoError: you are over your space quota, using 2053 MB of 2048 MB
Jan 18 18:00:03 wikiloop-doublecheck-prod app[web] info       at Connection.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/core/connection/pool.js:460:61)
Jan 18 18:00:03 wikiloop-doublecheck-prod app[web] info       at Connection.emit (events.js:311:20)
Jan 18 18:00:03 wikiloop-doublecheck-prod app[web] info       at Connection.EventEmitter.emit (domain.js:482:12)
Jan 18 18:00:03 wikiloop-doublecheck-prod app[web] info       at processMessage (/app/node_modules/mongoose/node_modules/mongodb/lib/core/connection/connection.js:368:10)
Jan 18 18:00:03 wikiloop-doublecheck-prod app[web] info       at TLSSocket.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/core/connection/connection.js:537:15)
Jan 18 18:00:03 wikiloop-doublecheck-prod app[web] info       at TLSSocket.emit (events.js:311:20)
Jan 18 18:00:03 wikiloop-doublecheck-prod app[web] info       at TLSSocket.EventEmitter.emit (domain.js:482:12)
Jan 18 18:00:03 wikiloop-doublecheck-prod app[web] info       at addChunk (_stream_readable.js:294:12)
Jan 18 18:00:03 wikiloop-doublecheck-prod app[web] info       at readableAddChunk (_stream_readable.js:275:11)
Jan 18 18:00:03 wikiloop-doublecheck-prod app[web] info       at TLSSocket.Readable.push (_stream_readable.js:209:10)
Jan 18 18:00:03 wikiloop-doublecheck-prod app[web] info       at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23) {
Jan 18 18:00:03 wikiloop-doublecheck-prod app[web] info     ok: 0,
Jan 18 18:00:03 wikiloop-doublecheck-prod app[web] info     errmsg: 'you are over your space quota, using 2053 MB of 2048 MB',
Jan 18 18:00:03 wikiloop-doublecheck-prod app[web] info     code: 8000,
Jan 18 18:00:03 wikiloop-doublecheck-prod app[web] info     codeName: 'AtlasError',
Jan 18 18:00:03 wikiloop-doublecheck-prod app[web] info     name: 'MongoError',
Jan 18 18:00:03 wikiloop-doublecheck-prod app[web] info     [Symbol(mongoErrorContextSymbol)]: {}
Jan 18 18:00:03 wikiloop-doublecheck-prod app[web] info   }
Jan 18 18:00:03 wikiloop-doublecheck-prod app[web] info }

```

**Comment by xinbenlv** [comment]
Mitigate: bump the MongoDB quota from 2GB to 5GB

Further resolution pending: 

1. shutdown US 2020 topic feed
2. auto-remove feed revisions after expiration.
3. down size MongoDB quota size
